<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Kommunikation" Id="{819753f2-3217-43d9-848a-d77cf7327dce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Kommunikation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Kommunikation">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>